<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.4.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProductLicenseKeyTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_license_key', function (Blueprint $table) {
            $table->increments('id');
            $table->string('shopify_store_id', 255)->nullable();
            $table->string('product_id', 255)->default('1');
            $table->text('product_name')->nullable();
            $table->string('license_key', 255)->nullable();
            $table->string('resold', 191);
            $table->nullableTimestamps();

            $table->index('license_key', 'product_license_key_license_key_index');

            

        });

        

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_license_key');
    }
}
